ConfigurationVersion: 1.0
UsePercentageChance: true
ItemToCatch: diamond
CatchChance:
  axolotl: 100.0
  bat: 100.0
  bee: 100.0
  blaze: 100.0
  cat: 100.0
  cavespider: 100.0
  chicken: 100.0
  cod: 100.0
  cow: 100.0
  creeper: 100.0
  dolphin: 100.0
  donkey: 100.0
  drowned: 100.0
  elderguardian: 100.0
  enderman: 100.0
  endermite: 100.0
  evoker: 100.0
  fox: 100.0
  frog: 100.0
  ghast: 100.0
  glowsquid: 100.0
  goat: 100.0
  guardian: 100.0
  hoglin: 100.0
  horse: 100.0
  husk: 100.0
  lama: 100.0
  magmacube: 100.0
  mule: 100.0
  mushroomcow: 100.0
  ocelot: 100.0
  panda: 100.0
  parrot: 100.0
  phantom: 100.0
  pig: 100.0
  piglin: 100.0
  pillager: 100.0
  polarbear: 100.0
  pufferfish: 100.0
  rabbit: 100.0
  ravager: 100.0
  salmon: 100.0
  sheep: 100.0
  shulker: 100.0
  silverfish: 100.0
  skeleton: 100.0
  skeletonhorse: 100.0
  slime: 100.0
  spider: 100.0
  squid: 100.0
  stray: 100.0
  strider: 100.0
  tadpole: 100.0
  traderlama: 100.0
  tropicalfish: 100.0
  turtle: 100.0
  vex: 100.0
  villager: 100.0
  vindicator: 100.0
  wanderingtrader: 100.0
  warden: 100.0
  witch: 100.0
  witherskeleton: 100.0
  wolf: 100.0
  zoglin: 100.0
  zombie: 100.0
  zombiehorse: 100.0
  zombievillager: 100.0
  zombifiedpiglin: 100.0
CatchItemCost:
  axolotl: 1
  bat: 1
  bee: 1
  blaze: 1
  cat: 1
  cavespider: 1
  chicken: 1
  cod: 1
  cow: 1
  creeper: 1
  dolphin: 1
  donkey: 1
  drowned: 1
  elderguardian: 1
  enderman: 1
  endermite: 1
  evoker: 1
  fox: 1
  frog: 1
  ghast: 1
  glowsquid: 1
  goat: 1
  guardian: 1
  hoglin: 1
  horse: 1
  husk: 1
  lama: 1
  magmacube: 1
  mule: 1
  mushroomcow: 1
  ocelot: 1
  panda: 1
  parrot: 1
  phantom: 1
  pig: 1
  piglin: 1
  pillager: 1
  polarbear: 1
  pufferfish: 1
  rabbit: 1
  ravager: 1
  salmon: 1
  sheep: 1
  shulker: 1
  silverfish: 1
  skeleton: 1
  skeletonhorse: 1
  slime: 1
  spider: 1
  squid: 1
  stray: 1
  strider: 1
  tadpole: 1
  traderlama: 1
  tropicalfish: 1
  turtle: 1
  vex: 1
  villager: 1
  vindicator: 1
  wanderingtrader: 1
  warden: 1
  witch: 1
  witherskeleton: 1
  wolf: 1
  zoglin: 1
  zombie: 1
  zombiehorse: 1
  zombievillager: 1
  zombifiedpiglin: 1
